spring:
  application:
    name: st-jwt-token

  data:
    mongodb:
      database: st_security
      host: localhost 
      password: c2VjXzIwWFgjMQ==
      username: st_sec_2OZI

server:
  port: 0
    
eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://eureka.server:9100/eureka

# use st_security
#db.grantRolesToUser("st-boot-jwt-20XX", [{ role: "dbOwner", db: "st_security" }])
#db.changeUserPassword("st_sec_2OZI", "c2VjXzIwWFgjMQ==")1